### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by ismaelbej** [bitpay/bitcoind-rpc#22]
Got this error logged, any idea how to avoid such error?

```
/mynode/node_modules/bitcoind-rpc/lib/index.js:70
     buf += data;
            ^

RangeError: Invalid string length
   at IncomingMessage.<anonymous> (/mynode/node_modules/bitcoind-rpc/lib/index.js:70:14)
   at emitOne (events.js:77:13)
   at IncomingMessage.emit (events.js:169:7)
   at readableAddChunk (_stream_readable.js:153:18)
   at IncomingMessage.Readable.push (_stream_readable.js:111:10)
   at HTTPParser.parserOnBody (_http_common.js:124:22)
   at Socket.socketOnData (_http_client.js:320:20)
   at emitOne (events.js:77:13)
   at Socket.emit (events.js:169:7)
   at readableAddChunk (_stream_readable.js:153:18)
   at Socket.Readable.push (_stream_readable.js:111:10)
   at TCP.onread (net.js:536:20)
```

**Comment by iBitcoin-se** [comment]
Received data is so big, try to split your RPC call into chunks
