### ISSUE TITLE
TypeError: Cannot read property &#39;toString&#39; of undefined

### ISSUE THREAD

**Issue by thackerronak** [bitpay/bitcoind-rpc#39]
Getting type error in lib file. 
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>TypeError: Cannot read property &#39;toString&#39; of undefined
            <br> &nbsp; &nbsp;at Array.str (/home/ubuntu/swap-node/node_modules/bitcoind-rpc/lib/index.js:260:18)
            <br> &nbsp; &nbsp;at RpcClient.&lt;anonymous&gt; (/home/ubuntu/swap-node/node_modules/bitcoind-rpc/lib/index.js:236:35)
            <br> &nbsp; &nbsp;at Bitcoin.sendTransaction (/home/ubuntu/swap-node/node_modules/bitcore-node/lib/services/bitcoind.js:1804:15)
            <br> &nbsp; &nbsp;at Node.self.(anonymous function) [as sendTransaction] (/home/ubuntu/swap-node/node_modules/bitcore-node/lib/node.js:223:27)
            <br> &nbsp; &nbsp;at TxController.send (/home/ubuntu/swap-node/node_modules/insight-api/lib/transactions.js:303:13)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/ubuntu/swap-node/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at next (/home/ubuntu/swap-node/node_modules/express/lib/router/route.js:137:13)
            <br> &nbsp; &nbsp;at Route.dispatch (/home/ubuntu/swap-node/node_modules/express/lib/router/route.js:112:3)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/ubuntu/swap-node/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at /home/ubuntu/swap-node/node_modules/express/lib/router/index.js:281:22
        </pre>
    </body>
</html>
```

**Comment by carnesen** [comment]
@thackerronak You'll need to provide more context for the problem you're encountering to have any chance of getting help with this. All we have to go on is an HTML snippet, which is confusing in and of itself because this library is only intended for use in Node.js.
